version: '3'
services:
  
  api:
    container_name: api
    build: .
    command: npm run dev
    environment:
      NODE_ENV: development
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
    volumes:
      - .:/app
    ports:
      - "80:3000"
    depends_on:
      - localstack

  localstack:
    container_name: localstack
    image: localstack/localstack
    environment:
      SERVICES: dynamodb:4000
      PORT_WEB_UI: 4586
      DATA_DIR: /tmp/localstack/data
    volumes:
      - "localstack:/tmp/localstack"

volumes:
  localstack: